# Copyright (c) 2016-present Sven Greb <development@svengreb.de>
# This source code is licensed under the MIT license found in the license file.

# Travis CI configuration.
# References:
#   1. https://docs.travis-ci.com/user/languages/javascript-with-nodejs

language: objective-c
notifications:
  email:
    on_success: never
    on_failure: change
script: "curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh"
